services:
  backend:
    build: ./backend
    container_name: eventro-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/eventro
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb: # ✅ same level as backend
    image: mongo:7.0
    container_name: eventro-mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - eventro-mongo-data:/data/db
  
  frontend:
     build: ./frontend
     container_name: eventro-frontend
     restart: unless-stopped
     ports:
       - "127.0.0.1:3000:80"
     depends_on:
       - backend

volumes:
  eventro-mongo-data:
